### ISSUE TITLE
请求数据失败了  有回调到当前的类吗  没看到有 可以封装一下吗

### ISSUE THREAD

**Issue by yang948045840** [jzh1996/mvvm#1]
请求数据失败了  有回调到当前的类吗  没看到有 可以封装一下吗

**Comment by jzh1996** [comment]
在fragment或者activity重写requestRrror方法可以接收回调

**Comment by ferch** [comment]
一个页面多个请求的时候，请求失败的回调怎么区分

**Comment by jzh1996** [comment]
> 一个页面多个请求的时候，请求失败的回调怎么区分

这个项目的网络请求框架设计的不太合理。有时间我把现在项目使用的网络请求框架单独封装一个模块更新一下

**Comment by ferch** [comment]
坐等大佬更新

**Comment by jzh1996** [comment]
> 坐等大佬更新

已经更新了哈，可以参考ViewBindingActivity看一下
